//! Neo4j Cypher export for graph database import.
//!
//! Generates MERGE statements that can be executed against a Neo4j instance
//! to recreate the dependency graph with typed nodes and relationship properties.

use std::path::PathBuf;

use super::{CodeGraph, EdgeKind};
use crate::error::Result;

/// Options for Neo4j Cypher export.
#[derive(Debug, Clone)]
pub struct CypherExportOptions {
    /// Output file path.
    pub output_path: PathBuf,
}

/// Escape single quotes in strings for Cypher string literals.
fn cypher_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\'', "\\'")
}

/// Map an EdgeKind to a Neo4j relationship type.
fn relationship_type(kind: &EdgeKind) -> &'static str {
    match kind {
        EdgeKind::Resolved => "IMPORTS",
        EdgeKind::Calls => "CALLS",
        EdgeKind::DocumentedBy => "DOCUMENTED_BY",
        EdgeKind::External => "EXTERNAL_DEP",
    }
}

/// Capitalize first letter of a language name for Neo4j labels.
fn language_label(lang_name: &str) -> String {
    let mut chars = lang_name.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => {
            let first: String = c.to_uppercase().collect();
            let rest: String = chars
                .filter(|ch| ch.is_alphanumeric())
                .map(|ch| ch.to_ascii_lowercase())
                .collect();
            format!("{}{}", first, rest)
        }
    }
}

/// Export the dependency graph as Neo4j Cypher MERGE statements.
///
/// Node labels: `:File:<Language>`.
/// Relationship types from EdgeKind: `:IMPORTS`, `:CALLS`, `:DOCUMENTED_BY`, `:EXTERNAL_DEP`.
pub fn export_cypher(graph: &CodeGraph, options: &CypherExportOptions) -> Result<()> {
    let mut cypher = String::new();

    cypher.push_str("// Codixing dependency graph — Neo4j Cypher export\n");
    cypher.push_str("// Generated by codixing graph --cypher\n\n");

    // Create constraint for uniqueness.
    cypher.push_str("CREATE CONSTRAINT IF NOT EXISTS FOR (f:File) REQUIRE f.path IS UNIQUE;\n\n");

    // Emit nodes.
    let nodes = graph.nodes_by_pagerank();
    for node in &nodes {
        if node.file_path.starts_with("__ext__:") {
            continue;
        }
        let path_esc = cypher_escape(&node.file_path);
        let lang_label = language_label(node.language.name());
        let community_str = match node.community {
            Some(c) => format!("{}", c),
            None => "null".to_string(),
        };
        cypher.push_str(&format!(
            "MERGE (n:File:{} {{path: '{}'}}) SET n.pagerank = {:.4}, n.community = {}, n.in_degree = {}, n.out_degree = {};\n",
            lang_label,
            path_esc,
            node.pagerank,
            community_str,
            node.in_degree,
            node.out_degree,
        ));
    }

    cypher.push('\n');

    // Emit edges.
    let edges = graph.all_edges();
    for (from, to, edge) in &edges {
        if from.starts_with("__ext__:") || to.starts_with("__ext__:") {
            continue;
        }
        let from_esc = cypher_escape(from);
        let to_esc = cypher_escape(to);
        let rel_type = relationship_type(&edge.kind);
        let raw_esc = cypher_escape(&edge.raw_import);
        let confidence = format!("{:?}", edge.confidence);
        let provenance = edge.confidence.provenance();

        cypher.push_str(&format!(
            "MATCH (a:File {{path: '{}'}}), (b:File {{path: '{}'}}) MERGE (a)-[:{} {{raw_import: '{}', confidence: '{}', provenance: '{}'}}]->(b);\n",
            from_esc, to_esc, rel_type, raw_esc, confidence, provenance,
        ));
    }

    std::fs::write(&options.output_path, &cypher)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::CodeGraph;
    use crate::language::Language;

    #[test]
    fn cypher_export_contains_merge_statements() {
        let mut g = CodeGraph::new();
        g.add_edge(
            "src/main.rs",
            "src/lib.rs",
            "crate::lib",
            Language::Rust,
            Language::Rust,
        );

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.cypher");
        let opts = CypherExportOptions {
            output_path: path.clone(),
        };

        export_cypher(&g, &opts).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("MERGE"));
        assert!(content.contains("src/main.rs"));
        assert!(content.contains("src/lib.rs"));
        assert!(content.contains(":IMPORTS"));
        assert!(content.contains(":File:Rust"));
    }

    #[test]
    fn cypher_escapes_single_quotes() {
        assert_eq!(cypher_escape("it's"), "it\\'s");
    }

    #[test]
    fn cypher_excludes_external_by_default() {
        let mut g = CodeGraph::new();
        g.add_edge(
            "src/main.rs",
            "src/lib.rs",
            "crate::lib",
            Language::Rust,
            Language::Rust,
        );
        g.add_external_edge("src/main.rs", "serde", Language::Rust);

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.cypher");
        let opts = CypherExportOptions {
            output_path: path.clone(),
        };

        export_cypher(&g, &opts).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(!content.contains("__ext__"));
        assert!(!content.contains("EXTERNAL_DEP"));
    }
}
